# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 360
  steps:
  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      ECHO ON
      source activate base
      conda create --yes --quiet --name pdal
    displayName: Create conda environment

  - script: |
      ECHO ON
      source activate pdal
      conda config --set always_yes True --set show_channel_urls True
      conda install --yes --quiet --name pdal -c conda-forge geotiff laszip nitro curl gdal cmake eigen ninja libgdal zstd numpy xz libxml2 laz-perf qhull sqlite hdf5 tiledb conda-build ninja -y
    displayName: Install PDAL dependencies
  - script: |
      source activate pdal
      echo "current directory:" `pwd`
      mkdir build
      cd build
      cmake   -G Ninja  \
        -DCMAKE_LIBRARY_PATH:FILEPATH="$CONDA_PREFIX/lib" \
        -DCMAKE_INCLUDE_PATH:FILEPATH="$CONDA_PREFIX/include" \
        -DPython3_ROOT_DIR:FILEPATH="$CONDA_PREFIX" \
        -DCMAKE_FIND_FRAMEWORK="NEVER" \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
        -DBUILD_PLUGIN_SQLITE=ON \
        -DBUILD_PLUGIN_PGPOINTCLOUD=ON \
        -DBUILD_PLUGIN_NITF=ON \
        -DBUILD_PLUGIN_PYTHON=ON \
        -DBUILD_PLUGIN_ICEBRIDGE=ON \
        -DBUILD_PLUGIN_PCL=OFF \
        -DBUILD_PLUGIN_GREYHOUND=ON \
        -DBUILD_PLUGIN_TILEDB=ON \
        -DWITH_LAZPERF=ON \
        -DWITH_ZSTD=ON \
        -DWITH_LASZIP=ON \
        ..
    displayName: 'CMake'
  - script: |
      cd build
      source activate pdal
      ninja
    displayName: 'Build'
  - script: |
      cd build
      source activate pdal
      ctest -V
    displayName: 'Test'
  - script: |
      export PDAL_TEST_DIR=`pwd`/test
      export INSTALL_DIR=`pwd`/install
      export PATH=$PATH:$INSTALL_DIR/bin
      cd build
      source activate pdal
      ls build/lib/*
      ninja install
      # Python extension testing
      #
      pip3 install packaging cython
      git clone https://github.com/PDAL/python.git pdal-python
      cd pdal-python
      git checkout 2.0.0
      python3 setup.py build
      LD_LIBRARY_PATH=$INSTALL_DIR/lib python3 setup.py test
    displayName: 'Python'
  - script: |
      export BASE=`pwd`
      for EXAMPLE in writing writing-filter writing-kernel writing-reader writing-writer
      do
          cd $BASE/examples/$EXAMPLE
          mkdir -p _build || exit 1
          cd _build || exit 1
          cmake -G "Ninja" .. -DPDAL_DIR=$BASE/install/lib/cmake/PDAL && ninja
      done
    displayName: 'Examples'


