
jobs:
- job: win
  pool:
    vmImage: vs2017-win2016
  timeoutInMinutes: 360
  steps:
    - powershell: |
        Write-Host "Installing CMake 3.14.4"
        Invoke-WebRequest https://cmake.org/files/v3.14/cmake-3.14.4-win64-x64.zip -OutFile C:\cmake-3.14.4-win64-x64.zip
        Expand-Archive C:\cmake-3.14.4-win64-x64.zip -DestinationPath C:\
        Rename-Item -Path C:\cmake-3.14.4-win64-x64 -NewName C:\cmake
        Write-Host "##vso[task.prependpath]C:\cmake\bin"
      displayName: 'Install CMake'
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - script: |
        ECHO ON
        call conda create --yes --quiet --name pdal
      displayName: Create conda environment

    - script: |
        ECHO ON
        call activate pdal
        call conda config --set always_yes True --set show_channel_urls True
        call conda config --add channels conda-forge
        call conda install --yes --quiet --name pdal -c conda-forge ninja
        call conda install --yes --quiet --name pdal -c conda-forge pdal --only-deps
      displayName: Install PDAL dependencies
    - script: |
        call activate pdal
        mkdir build
        pushd build
        cmake -G "Ninja" ^
            -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
            -DPDAL_PLUGIN_INSTALL_PATH:FILEPATH=%PDAL_PLUGIN_INSTALL_PATH% ^
            -DWITH_TESTS=ON ^
            -DCMAKE_VERBOSE_MAKEFILE=OFF ^
            -DCMAKE_LIBRARY_PATH:FILEPATH="%CONDA_PREFIX%/Library/lib" ^
            -DCMAKE_INCLUDE_PATH:FILEPATH="%CONDA_PREFIX%/Library/include" ^
            -DOPENSSL_ROOT_DIR=%CONDA_PREFIX%/Library ^
            -DPython3_ROOT_DIR:FILEPATH="%CONDA_PREFIX%" ^
            -DBUILD_PLUGIN_CPD=OFF ^
            -DBUILD_PLUGIN_GREYHOUND=ON ^
            -DBUILD_PLUGIN_ICEBRIDGE=ON ^
            -DBUILD_PLUGIN_MRSID=OFF ^
            -DBUILD_PLUGIN_NITF=ON ^
            -DBUILD_PLUGIN_PCL=ON ^
            -DBUILD_PLUGIN_PGPOINTCLOUD=ON ^
            -DBUILD_PLUGIN_OCI=OFF ^
            -DBUILD_PLUGIN_SQLITE=ON ^
            -DBUILD_PLUGIN_I3S=ON ^
            -DBUILD_PLUGIN_RIVLIB=OFF ^
            -DBUILD_PLUGIN_PYTHON=ON ^
            -DENABLE_CTEST=OFF ^
            -DWITH_LAZPERF=ON ^
            -DWITH_LZMA=ON ^
            -DLIBLZMA_LIBRARY:FILEPATH=%CONDA_PREFIX%\Library\lib\liblzma.lib ^
            -DWITH_LASZIP=ON ^
            -DORACLE_INCLUDE_DIR=%CONDA_PREFIX%/include ^
            -DORACLE_LIBRARY=%CONDA_PREFIX%/libs/oci.lib ^
            -DLazperf_DIR:FILEPATH=%CONDA_PREFIX%/Library/cmake ^
            -DHDF5_DIR:FILEPATH=%CONDA_PREFIX%/Library/cmake ^
            -DPCL_DIR:FILEPATH=%CONDA_PREFIX%/Library/cmake ^
            -DLazperf_DIR:FILEPATH=%CONDA_PREFIX%/Library/cmake ^
            -DWITH_ZLIB=ON ^
            -Dgtest_force_shared_crt=ON ^
            -DBUILD_PGPOINTCLOUD_TESTS=OFF ^
            -DBUILD_SQLITE_TESTS=OFF ^
            -DBUILD_I3S_TESTS=OFF ^
            -DBUILD_OCI_TESTS=OFF ^
            ..
    - script: |
        call activate pdal
        pushd build
        ninja
      displayName: 'Build'

